apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-schema
data:
  schema.sql: |
    CREATE TABLE users (
        id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
        username VARCHAR(255) NOT NULL,
        hash TEXT NOT NULL,
        cash DECIMAL(10, 2) NOT NULL DEFAULT 10000.00
    );

    CREATE UNIQUE INDEX username ON users (username);

    CREATE TABLE IF NOT EXISTS stocks (
        user_id INT NOT NULL,
        symbol VARCHAR(10) NOT NULL,
        name VARCHAR(255) NOT NULL,
        shares INT NOT NULL,
        FOREIGN KEY(user_id) REFERENCES users(id)
    );

    CREATE TABLE history (
        user_id INT NOT NULL,
        symbol VARCHAR(10) NOT NULL,
        name VARCHAR(255) NOT NULL,
        shares INT NOT NULL,
        price DECIMAL(10, 2) NOT NULL,
        operation VARCHAR(50) NOT NULL,
        timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(user_id) REFERENCES users(id)
    );