apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mysql
  name: {{ .Values.pod.mysql.name }}
spec:
  containers:
  - image: {{ .Values.pod.mysql.image }}
    name: {{ .Values.pod.mysql.name }}
    env:
    {{- range $key, $value := .Values.secret.mysql.data }}
    - name: {{ $key }}
      valueFrom:
        secretKeyRef:
          name: {{ $.Values.secret.mysql.name }}
          key: {{ $key }}
    {{- end }}
    resources: {}
    volumeMounts:
    - name: schema-volume
      mountPath: /docker-entrypoint-initdb.d
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: schema-volume
    configMap:
      name: mysql-schema