apiVersion: v1
data:
  {{- range $key, $value := .Values.secret.trading.data }}
  {{ $key }}: {{ $value | toString | b64enc }}
  {{- end }}
kind: Secret
metadata:
  name: {{ .Values.secret.trading.name }}

---

apiVersion: v1
data:
  {{- range $key, $value := .Values.secret.mysql.data }}
  {{ $key }}: {{ $value | toString | b64enc }}
  {{- end }}
kind: Secret
metadata:
  name: {{ .Values.secret.mysql.name }}