apiVersion: v1
kind: Service
metadata:
  labels:
    app: trading
  name: {{ .Values.service.trading.name }}
spec:
  ports:
  - port: {{ .Values.service.trading.port }}
    protocol: {{ .Values.service.trading.protocol }}
    targetPort: {{ .Values.service.trading.targetPort }}
  selector:
    app: trading
  type: {{ .Values.service.trading.type }}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: {{ .Values.service.mysql.name }}
spec:
  ports:
  - port: {{ .Values.service.mysql.port }}
    protocol: {{ .Values.service.mysql.protocol }}
    targetPort: {{ .Values.service.mysql.targetPort }}
  selector:
    app: mysql
  type: {{ .Values.service.mysql.type }}